# Generated by Django 4.0.3 on 2022-04-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Driver', 'verbose_name_plural': 'Drivers'},
        ),
        migrations.AddField(
            model_name='driver',
            name='cars',
            field=models.ManyToManyField(to='taxi.car'),
        ),
    ]
