# Generated by Django 4.0.5 on 2022-06-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='license_number',
            new_name='licence_number',
        ),
    ]
