# Generated by Django 5.0.1 on 2024-02-03 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='mad',
            new_name='manufacturer',
        ),
    ]
