# Generated by Django 5.0.1 on 2024-01-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="name",
            new_name="model",
        ),
    ]
