# Generated by Django 4.1.7 on 2023-03-18 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="manufacture",
            new_name="manufacturer",
        ),
    ]
