# Generated by Django 4.2.11 on 2024-03-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"ordering": ("first_name", "last_name")},
        ),
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
