# Generated by Django 4.1.2 on 2022-10-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='username',
            field=models.CharField(max_length=69, unique=True),
        ),
    ]
