# Generated by Django 4.1.7 on 2023-03-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(max_length=255),
        ),
    ]
