# Generated by Django 5.0.1 on 2024-02-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={},
        ),
        migrations.RemoveField(
            model_name='driver',
            name='license_numbers',
        ),
        migrations.AddField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manufactured',
            name='name',
            field=models.CharField(max_length=63),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(fields=('license_number',), name='unique_license_number'),
        ),
        migrations.AddConstraint(
            model_name='manufactured',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
    ]
