# Generated by Django 4.0.3 on 2022-04-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={},
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(fields=('license_number',), name='unique_license_number'),
        ),
    ]
