# Generated by Django 4.2.1 on 2023-05-27 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="license_number",
        ),
    ]
