# Generated by Django 4.2 on 2023-04-05 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='license_plate',
        ),
    ]
