# Generated by Django 5.0.2 on 2024-02-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='licenses_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
