# Generated by Django 5.0.2 on 2024-02-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={},
        ),
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name="driver",
            constraint=models.UniqueConstraint(
                fields=("license_number",), name="unique_license_number"
            ),
        ),
    ]
