# Generated by Django 4.1.7 on 2023-03-14 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="license_number",
        ),
    ]
