# Generated by Django 4.2.1 on 2023-05-08 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="manufacturer",
            old_name="county",
            new_name="country",
        ),
    ]
