# Generated by Django 4.2.3 on 2023-07-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manufacture',
            new_name='Manufacturer',
        ),
    ]
