# Generated by Django 4.2.2 on 2023-06-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ["manufacturer__name"]},
        ),
        migrations.AlterField(
            model_name="driver",
            name="licence_number",
            field=models.CharField(blank=True, max_length=63, null=True, unique=True),
        ),
    ]
