# Generated by Django 4.0.2 on 2023-02-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['username'], 'verbose_name': 'Driver', 'verbose_name_plural': 'Drivers'},
        ),
    ]
