# Generated by Django 4.2.6 on 2023-10-08 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Manufactures",
            new_name="Manufacturer",
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "driver", "verbose_name_plural": "drivers"},
        ),
    ]
