# Generated by Django 4.2.3 on 2023-07-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Driver'),
        ),
    ]
