# Generated by Django 4.2.7 on 2023-11-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name_plural': 'Books Collection'},
        ),
    ]
