# Generated by Django 4.1.7 on 2023-09-16 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="drivers",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
