# Generated by Django 4.0.2 on 2023-07-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='manufacture',
            new_name='manufacturer',
        ),
    ]
