# Generated by Django 4.1.2 on 2022-10-15 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="driver",
            new_name="drivers",
        ),
    ]
