# Generated by Django 5.0.2 on 2024-02-23 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"verbose_name": "car"},
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "driver"},
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={"verbose_name": "manufacturer"},
        ),
        migrations.AlterField(
            model_name="car",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to="taxi.manufacturer",
            ),
        ),
    ]
