# Generated by Django 4.1.3 on 2022-11-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manufacturer",
            options={
                "ordering": ["name"],
                "verbose_name": "Driver",
                "verbose_name_plural": "Drivers",
            },
        ),
    ]
