# Generated by Django 5.0.2 on 2024-02-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Manufacture",
            new_name="Manufacturer",
        ),
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ("model",)},
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "Driver"},
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={"ordering": ("-name",)},
        ),
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.CharField(blank=True, max_length=65, unique=True),
        ),
    ]
