# Generated by Django 4.1.5 on 2023-01-28 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manufacturer",
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=255)),
                (
                    "drivers",
                    models.ManyToManyField(
                        related_name="drivers", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manufacturers",
                        to="taxi.manufacturer",
                    ),
                ),
            ],
            options={
                "ordering": ["model"],
            },
        ),
    ]
