# Generated by Django 4.1.7 on 2023-03-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="model",
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.CharField(max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name="driver",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="country",
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
