# Generated by Django 4.2 on 2023-04-24 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_alter_driver_license_number_alter_manufacturer_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"verbose_name_plural": "Drivers"},
        ),
        migrations.AlterField(
            model_name="car",
            name="drivers",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="Driver"
            ),
        ),
    ]
