# Generated by Django 5.0 on 2023-12-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0002_alter_driver_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
