# Generated by Django 4.2.6 on 2023-10-08 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0002_rename_licence_number_driver_license_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "driver", "verbose_name_plural": "drivers"},
        ),
        migrations.RemoveField(
            model_name="manufacturer",
            name="coutry",
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="country",
            field=models.CharField(default="country", max_length=100),
        ),
        migrations.AlterField(
            model_name="car",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to="taxi.manufacturer",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="model",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
