# Generated by Django 4.0.2 on 2023-01-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_alter_driver_license_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Driver', 'verbose_name_plural': 'Drivers'},
        ),
        migrations.RemoveField(
            model_name='driver',
            name='verbose_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='verbose_name_plural',
        ),
    ]
