# Generated by Django 4.2.1 on 2023-05-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_remove_driver_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
