# Generated by Django 5.0.2 on 2024-02-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_rename_manufacture_manufacturer_alter_car_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(max_length=65),
        ),
    ]
