# Generated by Django 4.1.7 on 2023-03-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_alter_driver_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="licence_number",
        ),
    ]
