# Generated by Django 4.0.2 on 2023-07-16 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_alter_driver_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxi.manufacturer'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
