# Generated by Django 5.0.3 on 2024-03-26 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_alter_driver_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ("manufacturer", "model")},
        ),
    ]
