# Generated by Django 4.0.3 on 2022-04-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_rename_license_number_driver_licence_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='driver',
            name='unique_license_number',
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(fields=('licence_number',), name='unique_license_number'),
        ),
    ]
