# Generated by Django 4.1.2 on 2022-10-31 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_alter_driver_email_alter_driver_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="taxi.manufacture"
            ),
        ),
    ]
