# Generated by Django 4.1.7 on 2023-03-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0002_alter_driver_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={
                "ordering": ("username",),
                "verbose_name": "driver",
                "verbose_name_plural": "drivers",
            },
        ),
        migrations.AddField(
            model_name="driver",
            name="license_number",
            field=models.CharField(default="asfaf", max_length=255, unique=True),
        ),
    ]
