# Generated by Django 4.1.2 on 2022-10-17 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_rename_driver_car_drivers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="drivers",
            new_name="driver",
        ),
    ]
