# Generated by Django 4.1 on 2022-08-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_rename_licence_number_driver_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
