# Generated by Django 4.0.5 on 2022-06-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_alter_car_options_alter_driver_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='verbose_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='driver',
            name='verbose_name_plural',
            field=models.CharField(default='', max_length=256),
        ),
    ]
