# Generated by Django 4.1.2 on 2022-10-18 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_alter_car_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ["model"]},
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={
                "ordering": ["username"],
                "verbose_name": "driver",
                "verbose_name_plural": "drivers",
            },
        ),
    ]
