# Generated by Django 4.0.5 on 2022-07-02 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_manufacturer_driver_license_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Driver', 'verbose_name_plural': 'Drivers'},
        ),
        migrations.RemoveField(
            model_name='driver',
            name='verbose_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='verbose_name_plural',
        ),
    ]
