# Generated by Django 4.0.3 on 2022-04-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_alter_car_drivers'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(fields=('license_number',), name='license_number'),
        ),
    ]
