# Generated by Django 5.0 on 2023-12-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_alter_car_manufacturer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
