# Generated by Django 4.2.2 on 2023-06-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_alter_driver_options_alter_driver_license_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name_plural': 'Driver with license'},
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='License number'),
        ),
    ]
