# Generated by Django 4.2.2 on 2023-06-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0002_alter_car_options_alter_driver_licence_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="licence_number",
        ),
        migrations.AddField(
            model_name="driver",
            name="license_number",
            field=models.CharField(default=159, max_length=63, unique=True),
            preserve_default=False,
        ),
    ]
