# Generated by Django 5.0.1 on 2024-02-04 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_alter_driver_options_remove_driver_license_numbers_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Manufactured",
            new_name="Manufacturer",
        ),
        migrations.RenameField(
            model_name="car",
            old_name="manufactured",
            new_name="manufacturer",
        ),
    ]
