# Generated by Django 4.2.4 on 2023-08-10 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0002_alter_driver_options_alter_car_drivers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manufacturers",
                to="taxi.manufacturer",
            ),
        ),
    ]
