# Generated by Django 4.2.2 on 2023-06-22 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0002_alter_driver_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manufacturer",
            options={},
        ),
    ]
