# Generated by Django 4.2.7 on 2023-11-13 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0002_rename_licence_number_driver_license_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "Driver", "verbose_name_plural": "Drivers"},
        ),
    ]
