# Generated by Django 4.0.2 on 2023-12-01 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_alter_car_drivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='drivers',
            field=models.ManyToManyField(blank=True, related_name='drivers', to=settings.AUTH_USER_MODEL),
        ),
    ]
