# Generated by Django 4.1.5 on 2023-01-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_alter_manufacturer_options_car"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={
                "ordering": ["username"],
                "verbose_name": "Driver",
                "verbose_name_plural": "Drivers",
            },
        ),
    ]
