# Generated by Django 4.1.2 on 2022-10-31 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_alter_driver_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='driver',
            new_name='drivers',
        ),
    ]
