# Generated by Django 4.2.8 on 2023-12-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0002_alter_driver_password"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="driver",
            name="unique_driver_license_number",
        ),
        migrations.AlterField(
            model_name="driver",
            name="password",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name="driver",
            constraint=models.UniqueConstraint(
                fields=("license_number", "password"),
                name="unique_driver_license_number",
            ),
        ),
    ]
