# Generated by Django 5.0.3 on 2024-03-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_alter_driver_groups_alter_driver_user_permissions'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='driver',
            managers=[
            ],
        ),
    ]
