# Generated by Django 5.0.1 on 2024-01-30 11:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0002_alter_car_options_alter_driver_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={},
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={},
        ),
    ]
