# Generated by Django 4.0 on 2023-12-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_alter_driver_groups_alter_driver_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
