# Generated by Django 5.0.3 on 2024-03-12 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_alter_car_manufacturer_alter_manufacturer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="drivers",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
