# Generated by Django 4.0.2 on 2023-10-15 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_alter_driver_groups_alter_driver_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='manufactuter',
        ),
        migrations.AddField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taxi.manufacturer'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='username',
            field=models.CharField(default='user-1', max_length=63, unique=True),
        ),
    ]
