# Generated by Django 4.1.7 on 2023-03-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0003_alter_driver_license_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="verbose_name",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="verbose_name_plural",
        ),
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
