# Generated by Django 5.0.1 on 2024-01-07 18:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0003_alter_car_manufacturer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"verbose_name": "car", "verbose_name_plural": "cars"},
        ),
    ]
