# Generated by Django 4.2.1 on 2023-05-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_alter_manufacturer_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
