# Generated by Django 4.2.3 on 2023-07-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_alter_driver_license_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Driver', 'verbose_name_plural': 'Drivers'},
        ),
    ]
