# Generated by Django 4.0.3 on 2022-04-05 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_alter_driver_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='drivers',
        ),
        migrations.AddField(
            model_name='car',
            name='drivers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
