# Generated by Django 5.0.2 on 2024-02-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0003_alter_manufacturer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(max_length=65, unique=True),
        ),
    ]
