# Generated by Django 5.0.1 on 2024-02-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0003_rename_manufactured_manufacturer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.CharField(max_length=100),
        ),
    ]
