# Generated by Django 4.2 on 2023-04-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0003_alter_car_options_alter_car_drivers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={},
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name_plural": "Drivers"},
        ),
    ]
