# Generated by Django 4.0.2 on 2023-12-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_alter_car_drivers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='car',
            name='delf',
            field=models.CharField(default='', max_length=1),
        ),
    ]
