# Generated by Django 4.2.11 on 2024-03-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0003_alter_driver_license_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={
                "ordering": ("model",),
                "verbose_name": "car",
                "verbose_name_plural": "cars",
            },
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={
                "ordering": ("first_name", "last_name"),
                "verbose_name": "driver",
                "verbose_name_plural": "drivers",
            },
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={
                "ordering": ("name",),
                "verbose_name": "manufacturer",
                "verbose_name_plural": "manufacturers",
            },
        ),
    ]
