# Generated by Django 5.0.2 on 2024-02-29 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_alter_car_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['license_number']},
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='licenses_number',
            new_name='license_number',
        ),
    ]
