# Generated by Django 4.0.3 on 2022-04-05 22:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_alter_car_model_alter_manufacturer_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='cars',
        ),
        migrations.AddField(
            model_name='car',
            name='drivers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
