# Generated by Django 5.0 on 2023-12-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0003_alter_manufacturer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="licence_number",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
