# Generated by Django 4.2.1 on 2023-05-27 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0003_driver_license_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manufacturer",
            options={"ordering": ["name"]},
        ),
    ]
