# Generated by Django 4.0.5 on 2022-06-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0004_alter_driver_license_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={
                "ordering": ["username"],
                "verbose_name": "driver",
                "verbose_name_plural": "drivers",
            },
        ),
    ]
