# Generated by Django 4.2.3 on 2023-07-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0004_alter_driver_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manufactured',
            new_name='Manufacturer',
        ),
    ]
