# Generated by Django 4.2.7 on 2023-11-15 14:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0004_alter_car_drivers_alter_car_manufacturer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "driver", "verbose_name_plural": "drivers"},
        ),
    ]
