# Generated by Django 5.0.3 on 2024-03-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0004_alter_driver_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='driver',
            managers=[
            ],
        ),
    ]
