# Generated by Django 4.0.2 on 2023-06-21 04:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0004_alter_driver_groups_alter_driver_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name_plural': 'license numbers'},
        ),
        migrations.AlterField(
            model_name='car',
            name='drivers',
            field=models.ManyToManyField(related_name='cars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='license number'),
        ),
    ]
