# Generated by Django 4.2.7 on 2023-11-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0004_alter_car_drivers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
    ]
