# Generated by Django 4.2.3 on 2023-07-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0005_rename_manufactured_manufacturer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'driver', 'verbose_name_plural': 'drivers'},
        ),
    ]
