# Generated by Django 4.2.8 on 2023-12-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0005_alter_driver_additional_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="ASSCar1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mode", models.CharField(max_length=255)),
                ("manufacturerr", models.ManyToManyField(to="taxi.manufacturer")),
            ],
        ),
    ]
