# Generated by Django 4.1.7 on 2023-03-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0005_alter_driver_license_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
