# Generated by Django 4.0.2 on 2023-06-22 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0005_alter_driver_options_alter_car_drivers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name_plural': 'driver with license'},
        ),
    ]
