# Generated by Django 5.0.1 on 2024-02-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0005_alter_driver_license_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.CharField(max_length=63, null=True),
        ),
    ]
