# Generated by Django 5.0.3 on 2024-03-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0005_alter_driver_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
