# Generated by Django 4.1.2 on 2022-11-01 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0005_alter_driver_options_alter_car_manufacturer"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Manufacture",
            new_name="Manufacturer",
        ),
    ]
