# Generated by Django 4.2.8 on 2023-12-09 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0006_asscar1"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ASSCar1",
        ),
    ]
