# Generated by Django 4.1.7 on 2023-03-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0006_driver_license_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="license_number",
        ),
    ]
