# Generated by Django 5.0.3 on 2024-03-20 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0006_alter_driver_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="drivers",
            field=models.ManyToManyField(
                related_name="drivers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
