# Generated by Django 4.2.1 on 2023-05-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0006_alter_driver_license_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="model",
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="country",
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
