# Generated by Django 4.1.7 on 2023-03-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0007_remove_driver_license_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={},
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "driver", "verbose_name_plural": "drivers"},
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={},
        ),
        migrations.AddField(
            model_name="driver",
            name="license_number",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="driver",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.AddConstraint(
            model_name="driver",
            constraint=models.UniqueConstraint(
                fields=("license_number",), name="unique_number"
            ),
        ),
    ]
