# Generated by Django 4.1.2 on 2022-10-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={
                "ordering": ["model"],
                "verbose_name": "driver",
                "verbose_name_plural": "drivers",
            },
        ),
    ]
